name: Set Default PR Template
on:
  workflow_call:

jobs:
  set-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set PR template
        run: |
          mkdir -p .github
          echo "## Description


          ## What type of PR is this? (check all applicable)
          
          - [ ] 🍕 Feature
          - [ ] 🐛 Bug Fix
          - [ ] 🧑‍💻 Code Refactor
          - [ ] 🔥 Performance Improvements
          - [ ] ⏩ Revert
          
          ## Preview Link
          
          
          ## Asana Task
          
          
          ## Attachments & Documents
          
          
          ## Screenshots/Recordings
          
          
          ## [OPTIONAL] Are there any post-deployment tasks we need to perform?
          
          
          ## Other Notes" > .github/pull_request_template.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/pull_request_template.md
          git commit -m "Set default PR template"
          git push