name: var Check

on:
  workflow_call:

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for "var " in code
      run: |
        if grep -r "var " .; then
          echo "Code contains 'var '. Please fix before merging."
          exit 1
        else
          echo "Code is clean. Proceeding with the merge."
        fi

        # Additional diagnostic output
        echo "Current working directory: $(pwd)"
        echo "Contents of the directory: $(ls -l)"
