# This workflow checks for var occurances in .js files.

name: Check var

on:
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for "var" in JavaScript code
      run: |
        if grep -r --include=\*.js  -w -e '\bvar\b' .; then
          echo "Code contains 'var '. Please fix before merging."
          exit 1
        else
          echo "JavaScript code is clean. Proceeding with the merge."
        fi
