name: Live Settings Puller

on:
  workflow_call:
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set theme name as env variable
        run: echo "buildname=${{ secrets.SHOPIFY_THEME_NAME }}" >> $GITHUB_ENV
        id: themename

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: "latest"

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Pull Live Theme Settings
        env:
          SHOPIFY_FLAG_STORE: "${{ secrets.SHOPIFY_STORE }}"
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: | 
          shopify theme pull --live --only config/settings_data.json --store=${SHOPIFY_FLAG_STORE}
          shopify theme pull --live --only templates/*.json --store=${SHOPIFY_FLAG_STORE}

      - name: Push Theme to Main Branch
        env:
          SHOPIFY_FLAG_STORE: "${{ secrets.SHOPIFY_STORE }}"
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        uses: stefanzweifel/git-auto-commit-action@v4
